import io
import os
import tempfile
import unittest
import zipfile
from unittest import mock

from app import create_app
from bdd import extract_gpx_from_zip
from extensions import db


def _gpx(name='My Finds Pocket Query'):
    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<gpx version="1.0" xmlns="http://www.topografix.com/GPX/1/0">'
        f'<name>{name}</name><desc>Geocache file generated by Groundspeak, Inc.</desc>'
        '<author>Groundspeak</author>'
        '<wpt lat="48.85" lon="2.35"><name>GC1</name></wpt></gpx>'
    ).encode('utf-8')


class ExtractGpxFromZipTests(unittest.TestCase):
    """Pocket Query chargée telle que téléchargée (.zip) sur geocaching.com."""

    def setUp(self):
        self.tmpdir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmpdir.cleanup)
        app = create_app({'SQLALCHEMY_DATABASE_URI': f"sqlite:///{os.path.join(self.tmpdir.name, 'g.db')}"})
        with app.app_context():
            db.engine.dispose()
        # Les messages d'erreur passent par gettext : il faut un contexte de requête.
        ctx = app.test_request_context('/')
        ctx.push()
        self.addCleanup(ctx.pop)
        self.dest = os.path.join(self.tmpdir.name, 'out.gpx')

    def _zip(self, members):
        path = os.path.join(self.tmpdir.name, 'pq.zip')
        with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED) as zf:
            for name, content in members.items():
                zf.writestr(name, content)
        return path

    def _extracted(self):
        with open(self.dest, 'rb') as f:
            return f.read()

    def test_single_gpx_is_extracted(self):
        extract_gpx_from_zip(self._zip({'12345.gpx': _gpx()}), self.dest)
        self.assertEqual(self._extracted(), _gpx())

    def test_my_finds_is_preferred_over_wpts_and_other_files(self):
        path = self._zip({
            '12345-wpts.gpx': _gpx('Waypoints for Cache Listings'),
            'readme.txt': b'x',
            '12345.gpx': _gpx(),
        })
        extract_gpx_from_zip(path, self.dest)
        self.assertEqual(self._extracted(), _gpx())

    def test_zip_without_gpx_is_rejected(self):
        with self.assertRaisesRegex(ValueError, r'\.gpx'):
            extract_gpx_from_zip(self._zip({'readme.txt': b'x'}), self.dest)

    def test_oversized_member_is_rejected(self):
        with mock.patch('bdd.GPX_MAX_SIZE_BYTES', 10):
            with self.assertRaisesRegex(ValueError, '200'):
                extract_gpx_from_zip(self._zip({'12345.gpx': _gpx()}), self.dest)

    def test_corrupted_zip_is_rejected(self):
        path = os.path.join(self.tmpdir.name, 'bad.zip')
        with open(path, 'wb') as f:
            f.write(b'PK\x03\x04 not really a zip')
        with self.assertRaises(ValueError):
            extract_gpx_from_zip(path, self.dest)


class UploadZipRouteTests(unittest.TestCase):
    """Une archive invalide est refusée tout de suite, sans lancer d'import."""

    def setUp(self):
        self.tmpdir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmpdir.cleanup)
        self.app = create_app({'SQLALCHEMY_DATABASE_URI': f"sqlite:///{os.path.join(self.tmpdir.name, 'g.db')}"})
        with self.app.app_context():
            db.engine.dispose()

    def test_zip_without_gpx_returns_400(self):
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, 'w') as zf:
            zf.writestr('readme.txt', 'x')
        buf.seek(0)
        with mock.patch('blueprints.gpx.task_manager') as tm:
            resp = self.app.test_client().post('/upload', data={'file': (buf, 'pq.zip')})
        self.assertEqual(resp.status_code, 400)
        self.assertFalse(resp.get_json()['success'])
        tm.submit.assert_not_called()


if __name__ == '__main__':
    unittest.main()
